#### general settings
name: UFO-120_model_Fourier_FcaNet_v1
use_tb_logger: true
model: video_base4_m
distortion: sr
scale: 1
gpu_ids: [0]

#### datasets
datasets:
  train:
    name: indoor
    mode: video_samesize_lol
    interval_list: [1]
    random_reverse: false
    border_mode: false
    dataroot_GT: G:/UIE/dataset/UFO-120/train_val/hr_320x240
    dataroot_LQ: G:/UIE/dataset/UFO-120/train_val/lrd
    train_size: [320, 240]
    cache_keys: ~
    cache_data: true
#    padding: new_info

    N_frames: 5     # how many frames as a input.
    use_shuffle: true
    n_workers: 16  # per GPU
    batch_size: 8
    GT_size: 128     # size you want to crop out as input sample.
    LQ_size: 128
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: REDS4
    mode: video_samesize_lol
    dataroot_GT: G:/UIE/dataset/UFO-120/TEST/hr_320x240
    dataroot_LQ: G:/UIE/dataset/UFO-120/TEST/lrd
    cache_data: true
#    N_frames: 5
#    padding: new_info
    train_size: [320, 240]

#### network structures
network_G:
  which_model_G: FFGformer

#### path
path:
  root: ./
  strict_load: false
#  resume_state: auto

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 4e-4
  lr_scheme: MultiStepLR
  beta1: 0.9
  beta2: 0.99
  niter: 21000
  ft_tsa_only: 0
  warmup_iter: -1  # -1: no warm up
  lr_steps: [3000, 5000, 9000, 15000]
  eta_min: !!float 1e-7

  pixel_criterion: cb
  pixel_weight: 1.0
  val_freq: !!float 5e3

  manual.resize960x512_seed: 0

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1000
